version: 2
project_name: oq
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm64
    binary: oq
archives:
  - formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - LICENSE
      - README.md
homebrew_casks:
  - name: oq
    binary: oq
    homepage: https://github.com/plutov/oq
    repository:
      owner: plutov
      name: homebrew-tap
release:
  github:
    owner: plutov
    name: oq
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
